name: security scan
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 6"

env:
  GO_VERSION: 1.25.3
  TRIVY_VERSION: v0.61.1

jobs:
  security-scan:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
      - name: Trivy Scan
        run: |
          trivy fs --exit-code 1 --no-progress  --severity CRITICAL ./
      - name: Install govuln
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: govulncheck
        run: |
          govulncheck ./...
